services:
  - type: web
    name: backup-volabarato
    env: node
    buildCommand: NODE_ENV=development npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
